### ISSUE TITLE
这里什么意思？

### ISSUE THREAD

**Issue by ArtificialIdoit** [buppt/ChineseNER#11]
ChineseNER/data/renMinRiBao/data_renmin_word.py中，这一句：

sentences = re.split('[，。！？、‘’“”:]/[O]'.decode('utf-8'), texts)

[，。！？、‘’“”:]/[O] 这个正则式子里的/[O]如何理解？

**Comment by buppt** [comment]
> ChineseNER/data/renMinRiBao/data_renmin_word.py中，这一句：
> 
> sentences = re.split('[，。！？、‘’“”:]/[O]'.decode('utf-8'), texts)
> 
> [，。！？、‘’“”:]/[O] 这个正则式子里的/[O]如何理解？

emmmm。。。前面不是先按字做了标注么，匹配标点符号的话就是匹配   `。/O`    `？/O`   这样的。所以加了 后面这个/O。

**Comment by ArtificialIdoit** [comment]
> > ChineseNER/data/renMinRiBao/data_renmin_word.py中，这一句：
> > sentences = re.split('[，。！？、‘’“”:]/[O]'.decode('utf-8'), texts)
> > [，。！？、‘’“”:]/[O] 这个正则式子里的/[O]如何理解？
> 
> emmmm。。。前面不是先按字做了标注么，匹配标点符号的话就是匹配 `。/O` `？/O` 这样的。所以加了 后面这个/O。

明白了，thank you
