### ISSUE TITLE
为什么只保留了含有命名实体的行数据？

### ISSUE THREAD

**Issue by ArtificialIdoit** [buppt/ChineseNER#13]
ChineseNER/data/renMinRiBao/data_renmin_word.py中的85行到88行，为什么会只保留numNotO!=0的linedata？

**Comment by ArtificialIdoit** [comment]
我倒是有个猜测，但是不太敢确定

**Comment by ArtificialIdoit** [comment]
是因为负样本太多，所以去掉了无用信息，一种变相的数据增强？

**Comment by buppt** [comment]
> 是因为负样本太多，所以去掉了无用信息，一种变相的数据增强？

是的，其实就是把不包含实体的句子从训练集里删掉了。

**Comment by ArtificialIdoit** [comment]
> > 是因为负样本太多，所以去掉了无用信息，一种变相的数据增强？
> 
> 是的，其实就是把不包含实体的句子从训练集里删掉了。

好的，谢谢

**Comment by nuass** [comment]
分享下我的经验，在另一个NER项目里确实发现如果不去负样本，召回率会很低。所以去掉不包含实体的句子是必须的。

**Comment by ArtificialIdoit** [comment]
> 分享下我的经验，在另一个NER项目里确实发现如果不去负样本，召回率会很低。所以去掉不包含实体的句子是必须的。十分感谢，有时间我会试一下

**Comment by ArtificialIdoit** [comment]
> 分享下我的经验，在另一个NER项目里确实发现如果不去负样本，召回率会很低。所以去掉不包含实体的句子是必须的。

十分感谢，后续有时间我会尝试一下。
