### ISSUE TITLE
关于data_renmin_word.py里的x_padding

### ISSUE THREAD

**Issue by ArtificialIdoit** [buppt/ChineseNER#14]
这个x_padding会截取大于60长度的语句，这里是不是不太合理？

**Comment by buppt** [comment]
> 这个x_padding会截取大于60长度的语句，这里是不是不太合理？

这个是可以调的，我只是设置了60成了而已。。。

**Comment by ArtificialIdoit** [comment]
> > 这个x_padding会截取大于60长度的语句，这里是不是不太合理？
> 
> 这个是可以调的，我只是设置了60成了而已。。。

嗯，可以调我还是知道的，就是担心这个长度会不会截取句子的一部分，导致训练数据尤其是命名实体的不完整；另外就是这样做的同时也增加了一部分负样本吧，我不确定这些负样本会对训练结果造成怎样的影响。

**Comment by buppt** [comment]
> > > 这个x_padding会截取大于60长度的语句，这里是不是不太合理？
> > 
> > 
> > 这个是可以调的，我只是设置了60成了而已。。。
> 
> 嗯，可以调我还是知道的，就是担心这个长度会不会截取句子的一部分，导致训练数据尤其是命名实体的不完整；另外就是这样做的同时也增加了一部分负样本吧，我不确定这些负样本会对训练结果造成怎样的影响。

是这样的，你也可以查看所有的句子长度，然后选一个可以尽量包含全部句长的值，这个如何设置没有具体的规定，都可以试试看效果。

**Comment by ArtificialIdoit** [comment]
> > > > 这个x_padding会截取大于60长度的语句，这里是不是不太合理？
> > > 
> > > 
> > > 这个是可以调的，我只是设置了60成了而已。。。
> > 
> > 
> > 嗯，可以调我还是知道的，就是担心这个长度会不会截取句子的一部分，导致训练数据尤其是命名实体的不完整；另外就是这样做的同时也增加了一部分负样本吧，我不确定这些负样本会对训练结果造成怎样的影响。
> 
> 是这样的，你也可以查看所有的句子长度，然后选一个可以尽量包含全部句长的值，这个如何设置没有具体的规定，都可以试试看效果。

好的，我试试吧
