### ISSUE TITLE
预测问题

### ISSUE THREAD

**Issue by lushilun** [buppt/ChineseNER#9]
老哥，利用pytorch预测时，将每个单词的tag求出来后，直接找可构成组合吗？

**Comment by buppt** [comment]
> 老哥，利用pytorch预测时，将每个单词的tag求出来后，直接找可构成组合吗？

可以啊，求出BME来，就按规则构成组合就好了

**Comment by lushilun** [comment]
> > 老哥，利用pytorch预测时，将每个单词的tag求出来后，直接找可构成组合吗？
> 
> 可以啊，求出BME来，就按规则构成组合就好了

OK~thankU，有没有发现不连续情况呢？比如：“M_nt” 后面可能直接跟着 “O”

**Comment by buppt** [comment]
有可能会有的，这种情况按照规则不会提取出来 @lushilun

**Comment by lushilun** [comment]
> 有可能会有的，这种情况按照规则不会提取出来 @lushilun

嗯嗯，那针对于这种情况，您有没有一些较好的方法能够解决呢？还是直接遗弃了这种情况呢？

**Comment by buppt** [comment]
直接遗弃了 @lushilun

**Comment by lushilun** [comment]
> 直接遗弃了 @lushilun

欧克~Thank U

**Comment by alexanderwjz** [comment]
![image](https://user-images.githubusercontent.com/16386686/54803565-f4663100-4caa-11e9-996f-869d0ff43697.png)
测试输入大段文本抛错
